CodeBase/WfmWebPortal/Lms.Web.Portal/Controllers/WorkforceTrainningController.cs
using Lms.Web.Portal.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Wfm.App.BL;
using Wfm.App.Core;
using Wfm.App.Core.Model;

namespace Lms.Web.Portal.Controllers
{
    [SessionExpire]
    [WfmAuthorize]
    public class WorkforceTrainningController : Controller
    {
        private IBaseBL baseBL;

        public WorkforceTrainningController(IBaseBL baseBL)
        {
            this.baseBL = baseBL;
        }

        public ActionResult TrainningMaster()
        {
            TrainningByDepartments metaData = new TrainningByDepartments();

            AccountValidateUser_Result loggedin_user = Session["USER"] as AccountValidateUser_Result;
            var deptList = this.baseBL.DepartmentBL.GetDepartmentByCompanyId(loggedin_user.COMPANY_ID);
            var defaultBind = deptList.Select(x => x.DEPT_ID).FirstOrDefault();
            metaData.DEPARTMENT_ID = defaultBind;
            metaData.Departments = new SelectList(deptList, "DEPT_ID", "DEPT_NAME");
            metaData.Buildings = new SelectList(baseBL.ManPowerRequestBL.GetBuildings(), "BUILDING_ID", "BUILDING_NAME");
            return View(metaData);
        }

        public ActionResult GetTrainningMasterByDeptId(Guid deptId, Guid? sub_dept_id)
        {
            List<TrainningMasterMetaData> trainnings = this.baseBL.WorkforceTrainningBL.GetTrainningMaster(deptId, sub_dept_id);
            return PartialView("_TrainningList", trainnings);
        }
        public ActionResult GetTrainningMasterByDeptId_N()
        {
            List<TrainningMasterMetaData> trainnings = this.baseBL.WorkforceTrainningBL.GetTrainningMaster_N();
            return PartialView("_TrainningList", trainnings);
        }
        public ActionResult AddTrainning()
        {
            AddTrainningMetaData addTrainning = new AddTrainningMetaData();
            AccountValidateUser_Result loggedin_user = Session["USER"] as AccountValidateUser_Result;
            var deptList = this.baseBL.DepartmentBL.GetDepartmentByCompanyId(loggedin_user.COMPANY_ID);
            addTrainning.Departments = new SelectList(deptList, "DEPT_ID", "DEPT_NAME");
            addTrainning.Buildings = new SelectList(baseBL.ManPowerRequestBL.GetBuildings(), "BUILDING_ID", "BUILDING_NAME");
            return View("AddTrainningName", addTrainning);
        }

        [HttpPost]
        public ActionResult AddTrainningName(AddTrainningMetaData addTrainning)
        {
            AccountValidateUser_Result loggedin_user = Session["USER"] as AccountValidateUser_Result;
            Guid companyId = loggedin_user.COMPANY_ID;
            addTrainning.CMP_ID = companyId;
            addTrainning.CREATED_BY = loggedin_user.USER_LOGIN_ID;
            if (baseBL.WorkforceTrainningBL.AddTrainningMaster(addTrainning))
            {
                ViewData["result"] = "success";
                addTrainning.Departments = new SelectList(baseBL.DepartmentBL.GetDepartmentByCompanyId(loggedin_user.COMPANY_ID), "DEPT_ID", "DEPT_NAME");
                addTrainning.Buildings = new SelectList(baseBL.ManPowerRequestBL.GetBuildings(), "BUILDING_ID", "BUILDING_NAME");
                return View("AddTrainningName", addTrainning);
            }
            addTrainning.Departments = new SelectList(baseBL.DepartmentBL.GetDepartmentByCompanyId(loggedin_user.COMPANY_ID), "DEPT_ID", "DEPT_NAME");
            addTrainning.Buildings = new SelectList(baseBL.ManPowerRequestBL.GetBuildings(), "BUILDING_ID", "BUILDING_NAME");
            return View("AddTrainningName", addTrainning);
        }

        [HttpGet]
        public ActionResult EditTrainning(Guid id)
        {
            AddTrainningMetaData addTrainning = new AddTrainningMetaData();
            AccountValidateUser_Result loggedin_user = Session["USER"] as AccountValidateUser_Result;
            addTrainning = baseBL.WorkforceTrainningBL.GetTrainningMasterByTrainningId(loggedin_user.COMPANY_ID, id);
            addTrainning.Departments = new SelectList(baseBL.DepartmentBL.GetDepartmentByCompanyId(loggedin_user.COMPANY_ID), "DEPT_ID", "DEPT_NAME");
            ViewBag.SubDepartments = new SelectList(baseBL.SubDepartmentBL.GetSubDepartmentsByDeptId(addTrainning.DEPT_ID), "SUBDEPT_ID", "SUBDEPT_NAME", addTrainning.SUBDEPT_ID);
            addTrainning.Buildings = new SelectList(baseBL.ManPowerRequestBL.GetBuildings(), "BUILDING_ID", "BUILDING_NAME");
            return View(addTrainning);
        }

        [HttpPost]
        public ActionResult EditTrainning(AddTrainningMetaData trainning)
        {
            AddTrainningMetaData addTrainning = new AddTrainningMetaData();
            AccountValidateUser_Result loggedin_user = Session["USER"] as AccountValidateUser_Result;
            Guid companyId = loggedin_user.COMPANY_ID;
            trainning.UPDATED_BY = loggedin_user.USER_LOGIN_ID;
            if (baseBL.WorkforceTrainningBL.UpdateTrainningMaster(trainning))
            {
                ViewData["result"] = "success";
                addTrainning.Departments = new SelectList(baseBL.DepartmentBL.GetDepartmentByCompanyId(loggedin_user.COMPANY_ID), "DEPT_ID", "DEPT_NAME");
                ViewBag.SubDepartments = new SelectList(baseBL.SubDepartmentBL.GetSubDepartmentsByDeptId(addTrainning.DEPT_ID), "SUBDEPT_ID", "SUBDEPT_NAME", addTrainning.SUBDEPT_ID);
                addTrainning.Buildings = new SelectList(baseBL.ManPowerRequestBL.GetBuildings(), "BUILDING_ID", "BUILDING_NAME");
                return View("EditTrainning", addTrainning);
            }
            trainning.Departments = new SelectList(this.baseBL.DepartmentBL.GetDepartmentByCompanyId(loggedin_user.COMPANY_ID), "DEPT_ID", "DEPT_NAME");
            addTrainning.Buildings = new SelectList(baseBL.ManPowerRequestBL.GetBuildings(), "BUILDING_ID", "BUILDING_NAME");
            return View(addTrainning);

        }

        [HttpGet]
        public ActionResult AddTrainningWorkforce()
        {
            AccountValidateUser_Result loggedin_user = Session["USER"] as AccountValidateUser_Result;
            TrainningWorkforceMetaData trainningWorkforce = new TrainningWorkforceMetaData();
            ViewBag.RowCount = 0;
            trainningWorkforce.Departments = new SelectList(this.baseBL.DepartmentBL.GetDepartmentByCompanyId(loggedin_user.COMPANY_ID), "DEPT_ID", "DEPT_NAME");
            ViewBag.EmployeeTypes = new SelectList(baseBL.ManPowerRequestBL.GetEmpTypes(), "WF_EMP_TYPE", "EMP_TYPE");
            ViewBag.EmpName = new List<SelectListItem>();
            ViewBag.Buildings = new SelectList(baseBL.ManPowerRequestBL.GetBuildings(), "BUILDING_ID", "BUILDING_NAME");
            List<AddWorkforceMappingTrainning> trainnings = new List<AddWorkforceMappingTrainning>
            {
                new AddWorkforceMappingTrainning
                {
                    TrainningMasterByDepart= new SelectList(baseBL.WorkforceTrainningBL.GetTrainningMasterByDepartId(new Guid(), loggedin_user.COMPANY_ID), "TRAINNING_ID", "TRAINNING_NAME")
                }
            };
            trainningWorkforce.ListMetaDatas = trainnings;
            return View(trainningWorkforce);
        }

        [HttpPost]
        [Authorize]
        public ActionResult AddTrainningWorkforce(TrainningWorkforceMetaData model, HttpPostedFileBase PHOTO)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (model.PHOTOfile != null)
            {
                System.IO.Stream fs = model.PHOTOfile.InputStream;
                System.IO.BinaryReader br = new System.IO.BinaryReader(fs);
                model.PHOTO = br.ReadBytes((Int32)fs.Length);
                ModelState.Remove("PHOTOfile");
            }
            AccountValidateUser_Result loggedin_user = Session["USER"] as AccountValidateUser_Result;
            ModelState.Remove("WF_EMP_TYPE");
           
            model.CMP_ID = loggedin_user.COMPANY_ID;
            model.CREATED_BY = loggedin_user.USER_LOGIN_ID;
           
            var redirectUrl = new UrlHelper(Request.RequestContext).Action("WorkforceTraining", "TrainningWorkforce");
            if (baseBL.WorkforceTrainningBL.AddWorkforceTrainning(model))
                ViewData["result"] = "success";

            return AddTrainningWorkforce();
            
        }

        public ActionResult AddWorkforceTrainningByDeptId(string row, Guid deptId, Guid sub_Id)
        {
            ViewBag.RowNumber = Convert.ToInt32(row);
            AccountValidateUser_Result loggedin_user = Session["USER"] as AccountValidateUser_Result;
            AddWorkforceTrainningMetaData addTrainning = new AddWorkforceTrainningMetaData();
            addTrainning.Departments = new SelectList(this.baseBL.DepartmentBL.GetDepartmentByCompanyId(loggedin_user.COMPANY_ID), "DEPT_ID", "DEPT_NAME", deptId);
            addTrainning.TrainningMasterByDepart = new SelectList(baseBL.WorkforceTrainningBL.GetTrainningMasterByDepartId1(deptId, sub_Id, loggedin_user.COMPANY_ID), "TRAINNING_ID", "TRAINNING_NAME");

            return PartialView("_AddTrainning", addTrainning);
        }

        [HttpGet]
        public JsonResult GetTrainningBydeptId(Guid deptId, Guid sub_deptId)
        {
            var result = baseBL.WorkforceTrainningBL.GetTrainningMasterByDepartId(deptId, sub_deptId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult TrainningWorkforce()
        {
            TrainningWorkforceMetaData trainning = new TrainningWorkforceMetaData();
            AccountValidateUser_Result loggedin_user = Session["USER"] as AccountValidateUser_Result;
            trainning.Departments = new SelectList(baseBL.DepartmentBL.GetDepartmentByCompanyId(loggedin_user.COMPANY_ID), "DEPT_ID", "DEPT_NAME");
            ViewBag.EmployeeTypes = new SelectList(baseBL.ManPowerRequestBL.GetEmpTypes(), "WF_EMP_TYPE", "EMP_TYPE");

CodeBase/WfmWebPortal/Lms.Web.Portal/Views/WorkforceTrainning/AddTrainningName.cshtml
@model Wfm.App.Core.Model.AddTrainningMetaData

@{
    ViewBag.Title = "Workforce Training - Add";
}

<section class="content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="breadcrumb breadcrumb-style ">
                        <li class="breadcrumb-item">
                            <h4 class="page-title">Training Master</h4>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="/WorkforceTrainning/TrainningMaster">
                                <i class="fas fa-layer-group"></i>Workforce Training
                            </a>
                        </li>
                        <li class="breadcrumb-item active">Add</li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                <strong>Add</strong> Training
                            </h2>
                        </div>
                        <div class="body">
                            @using (Html.BeginForm("AddTrainningName", "WorkforceTrainning", FormMethod.Post, new { @id = "UserCreate", @class = "login100-form validate-form" }))
                            {
                                @Html.HiddenFor(m => m.TRAINNING_ID)
                           
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <div class="form-line">
                                            @Html.LabelFor(x => x.TRAINNING_NAME, "Training Name", new { @class = "required" })
                                            @Html.TextBoxFor(m => m.TRAINNING_NAME, "", new { @class = "form-control", @type = "text", required = "true" })
                                            @Html.ValidationMessageFor(m => m.TRAINNING_NAME)
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <div class="form-line">
                                            @Html.LabelFor(x => x.EXPECTED_DATE, "Expected Date", new { @class = "required" })
                                            @Html.TextBoxFor(m => m.EXPECTED_DATE, "{0:mm/dd/yyyy}", new { @class = "datepicker form-control", required = "true" })
                                            @Html.ValidationMessageFor(m => m.EXPECTED_DATE)
                                        </div>
                                    </div>
                                </div>
                            </div>

                                <div class="col-lg-12 p-t-20 text-center">
                                    <button type="submit" id="submit" class="btn btn-primary waves-effect m-r-15">Submit</button>
                                    <button type="button" id="cancel" class="btn btn-danger waves-effect">Cancel</button>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@*<script src="~/Scripts/jquery.validate.min.js"></script>*@
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script type="text/javascript">
    $(function () {

      var msg = '@ViewData["result"]';
              if (msg == 'success')
              {
                  alert("Trainning Details Submitted Successfully.");
                  window.location.href = "@Url.Action("TrainningMaster", "WorkforceTrainning")";
              }
    });
</script>
<script>

    $(document).ready(function () {
        $("select[required]").css({ position: "absolute", display: "inline", height: 0, padding: 0, width: 0 });
        $('#DEPT_ID').find('option').not(':first').remove();
        getSubDeptbyDeptId();
    });

    function onBuildingChange() {
        var buildingId = $("#BUILDING_ID option:selected").val();
        $.get('/ManPowerRequest/GetFloorByBuildingId?buildingId=' + buildingId, function (data) {
            $('#DEPT_ID').find('option').not(':first').remove();
            $.each(data, function (i, item) {
                $('#DEPT_ID').append($('<option>', {
                    value: item.DEPT_ID,
                    text: item.DEPT_NAME
                }));
            });
            $('#DEPT_ID').formSelect();
        });
    }

    $("#cancel").click(function () {
        window.location.href = "/WorkforceTrainning/TrainningMaster";
    });
    $("#DEPT_ID").change(function () {
        getSubDeptbyDeptId();
    });

    function getSubDeptbyDeptId() {
        var DEPARTMENT_ID = $("#DEPT_ID").val();
        if (DEPARTMENT_ID != null) {
            $.get('/Dashboard/GetSubDepartmentByDepartmentId?departmentId=' + DEPARTMENT_ID, function (data) {
                $('#SUBDEPT_ID').find('option').not(':first').remove();
                $.each(data, function (i, item) {
                    $('#SUBDEPT_ID').append($('<option>', {
                        value: item.SUBDEPT_ID,
                        text: item.SUBDEPT_NAME
                    }));
                });
                $('#SUBDEPT_ID').formSelect();
            });
        } else {
            $('#SUBDEPT_ID').find('option').not(':first').remove();
            $('#SUBDEPT_ID').formSelect();
        }
    }
   
</script>

CodeBase/WfmWebPortal/Lms.Web.Portal/Views/WorkforceTrainning/EditTrainning.cshtml
@model Wfm.App.Core.Model.AddTrainningMetaData

@{
    ViewBag.Title = "Workforce Training - Edit";
}

<section class="content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="breadcrumb breadcrumb-style ">
                        <li class="breadcrumb-item">
                            <h4 class="page-title">Training Master</h4>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="/WorkforceTrainning/TrainningMaster">
                                <i class="fas fa-layer-group"></i>Workforce Training
                            </a>
                        </li>
                        <li class="breadcrumb-item active">Edit</li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                <strong>Edit</strong> Training
                            </h2>
                        </div>
                        <div class="body">
                            @using (Html.BeginForm("EditTrainning", "WorkforceTrainning", FormMethod.Post, new { @id = "UserCreate", @class = "login100-form validate-form" }))
                            {
                                @Html.HiddenFor(m => m.TRAINNING_ID)
                           
                            <div class="row clearfix">
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <div class="form-line">
                                            @Html.LabelFor(x => x.TRAINNING_NAME, "Training Name", new { @class = "required" })
                                            @Html.TextBoxFor(m => m.TRAINNING_NAME, "", new { @class = "form-control", @type = "text" })
                                            @Html.ValidationMessageFor(m => m.TRAINNING_NAME)
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <div class="form-line">

                                            @Html.LabelFor(m => m.EXPECTED_DATE, "Expected Date", new { @class = "required" })
                                            @Html.TextBoxFor(m => m.EXPECTED_DATE, "{0: dd/MM/yyyy}", new { @class = "form-control datepicker" })
                                            @Html.ValidationMessageFor(m => m.EXPECTED_DATE)
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="form-group">
                                        <div class="form-line">
                                            <label>Status <span class="text-danger">*</span></label>
                                            @Html.DropDownListFor(x => x.STATUS, new List<SelectListItem>
                                                                            {
                                                                                new SelectListItem{ Text="Yes", Value = "Y" },
                                                                                new SelectListItem{ Text="No", Value = "N" }
                                                                             }, "-- Select Status--", new { required = "true" })
                                            @Html.ValidationMessageFor(m => m.STATUS)
                                        </div>
                                    </div>
                                </div>

                            </div>
                                <div class="col-lg-12 p-t-20 text-center">
                                    <button type="submit" id="submit" class="btn btn-primary waves-effect m-r-15">Update</button>
                                    <button type="button" id="cancel" onclick="btnCancel()" class="btn btn-danger waves-effect">Cancel</button>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@*<script src="~/Scripts/jquery.validate.min.js"></script>*@
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script type="text/javascript">
    $(function () {
      var msg = '@ViewData["result"]';
              if (msg == 'success')
              {
                  window.location.href = "@Url.Action("TrainningMaster", "WorkforceTrainning")";
                  alert("Trainning Details Updated Successfully.");
              }
    });
</script>
<script>
    $(document).ready(function () {
      
    })
    $(window).on('load', function () {
        $(".page-loader-wrapper").remove();
    });
    function btnCancel() {
        window.location.href = "/WorkforceTrainning/TrainningMaster";
    }
    $("#DEPT_ID").change(function () {
        getSubDeptbyDeptId();
    });

    function getSubDeptbyDeptId() {
        var DEPARTMENT_ID = $("#DEPT_ID").val();
        if (DEPARTMENT_ID != null) {
            $.get('/Dashboard/GetSubDepartmentByDepartmentId?departmentId=' + DEPARTMENT_ID, function (data) {
                $('#SUBDEPT_ID').find('option').not(':first').remove();
                $.each(data, function (i, item) {
                    $('#SUBDEPT_ID').append($('<option>', {
                        value: item.SUBDEPT_ID,
                        text: item.SUBDEPT_NAME
                    }));
                });
                $('#SUBDEPT_ID').formSelect();
            });
        } else {
            $('#SUBDEPT_ID').find('option').not(':first').remove();
            $('#SUBDEPT_ID').formSelect();
        }
    }

    function onBuildingChange() {
        var buildingId = $("#BUILDING_ID option:selected").val();
        $.get('/ManPowerRequest/GetFloorByBuildingId?buildingId=' + buildingId, function (data) {
            $('#DEPT_ID').find('option').not(':first').remove();
            $('#SUBDEPT_ID').find('option').not(':first').remove();
            $.each(data, function (i, item) {
                $('#DEPT_ID').append($('<option>', {
                    value: item.DEPT_ID,
                    text: item.DEPT_NAME
                }));
            });
            $('#DEPT_ID').formSelect();
            $('#SUBDEPT_ID').formSelect();
        });
    }
</script>

CodeBase/WfmWebPortal/Lms.Web.Portal/Views/WorkforceTrainning/TrainningMaster.cshtml
@model Wfm.App.Core.Model.TrainningByDepartments

@{
    ViewBag.Title = "Workforce Tranning - Master";
}

<h2>TrainningMaster</h2>

<section class="content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="breadcrumb breadcrumb-style ">
                        <li class="breadcrumb-item">
                            <h4 class="page-title">Training Master</h4>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="/WorkforceTrainning/AddTrainning">
                                <i class="fas fa-layer-group"></i> Workforce Training
                            </a>
                        </li>
                        <li class="breadcrumb-item active">Create</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            <strong>All</strong> Training
                        </h2>
                    </div>
                    <div class="row col-sm-12" style="display:none">
                        <div class="col-sm-3">
                            <div class="form-group">
                                <div class="form-line">
                                    @Html.LabelFor(x => x.BUILDING_ID, "Unit")
                                    @Html.DropDownListFor(x => x.BUILDING_ID, Model.Buildings, "-- Select--", new { id = "BUILDING_ID", required = "true", @onchange = "onBuildingChange()" })
                                    @Html.ValidationMessageFor(m => m.BUILDING_ID)
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group">
                                <div class="form-line">
                                    @Html.LabelFor(x => x.DEPARTMENT_ID, "Department")
                                    @Html.DropDownListFor(x => x.DEPARTMENT_ID, Model.Departments, "-- Select --", new { required = "true" })
                                    @Html.ValidationMessageFor(m => m.DEPARTMENT_ID)
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group">
                                <div class="form-line">
                                    @Html.LabelFor(x => x.SUBDEPARTMENT_ID, "Sub Department")
                                    @Html.DropDownListFor(x => x.SUBDEPARTMENT_ID, Enumerable.Empty<SelectListItem>(), "All", new { required = "true" })
                                    @Html.ValidationMessageFor(m => m.SUBDEPARTMENT_ID)
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-3" style="margin-top:20px">
                            <div class="form-group">
                                <div class="form-line">
                                    <button type="button" class="btn btn-primary" onclick="GetTrainnings()">Search</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="body" id="tblBody">
                        
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</section>
<script>
    $(document).ready(function () {
        GetTrainnings();
    });
    function onBuildingChange() {
        var buildingId = $("#BUILDING_ID option:selected").val();
        $.get('/ManPowerRequest/GetFloorByBuildingId?buildingId=' + buildingId, function (data) {
            $('#DEPARTMENT_ID').find('option').not(':first').remove();
            $.each(data, function (i, item) {
                $('#DEPARTMENT_ID').append($('<option>', {
                    value: item.DEPT_ID,
                    text: item.DEPT_NAME
                }));
            });
            $('#DEPARTMENT_ID').formSelect();
        });
    }

    $("#DEPARTMENT_ID").change(function () {
        getSubDeptbyDeptId();
    });

    function getSubDeptbyDeptId() {
        var DEPARTMENT_ID = $("#DEPARTMENT_ID").val();
        if (DEPARTMENT_ID != null) {
            $.get('/Dashboard/GetSubDepartmentByDepartmentId?departmentId=' + DEPARTMENT_ID, function (data) {
                $('#SUBDEPARTMENT_ID').find('option').not(':first').remove();
                $.each(data, function (i, item) {
                    $('#SUBDEPARTMENT_ID').append($('<option>', {
                        value: item.SUBDEPT_ID,
                        text: item.SUBDEPT_NAME
                    }));
                });
                $('#SUBDEPARTMENT_ID').formSelect();
                //GetTrainnings();
            });
        } else {
            $('#SUBDEPARTMENT_ID').find('option').not(':first').remove();
            $('#SUBDEPARTMENT_ID').formSelect();
            //GetTrainnings();
        }
    }

    $("#SUBDEPARTMENT_ID").change(function () {
        var DEPARTMENT_ID = $("#DEPARTMENT_ID").val();
        if (DEPARTMENT_ID != null) {
            /*GetTrainnings();*/
        }
    });

    function GetTrainnings() {
        //var BUILDING_ID = $("#BUILDING_ID").val();
        //var DEPARTMENT_ID = $("#DEPARTMENT_ID").val();
        //var SUBDEPT_ID = $("#SUBDEPARTMENT_ID").val();
        //if (DEPARTMENT_ID !== "") {
            $("#tblBody").empty();
            $.ajax(
                {
                    type: 'Get',
                    url: '/WorkforceTrainning/GetTrainningMasterByDeptId_N',
                    success:
                        function (response) {
                            $("#tblBody").append(response);
                        },
                    error:
                        function (response) {
                            alert("Error: " + response);
                        }
                });
        //}
    }
</script>

CodeBase/WfmWebPortal/Lms.Web.Portal/Views/WorkforceTrainning/_TrainningList.cshtml
@model List<Wfm.App.Core.Model.TrainningMasterMetaData>

<div class="table-responsive">
    <table id="tableExport" class="table table-bordered table-striped table-hover js-basic-example dataTable" width="100%">
        <thead>
            <tr>
                <th style="width:5%">#</th>
                @*<th style="width:30%"> Company Name </th>*@
                @*<th style="width:auto"> Department Name </th>
                <th style="width:auto"> Sub Department Name </th>*@
                <th style="width:15%"> Training Name </th>
                <th style="width:15%"> Expected Date</th>
                <th style="width:15%"> Status </th>
                <th style="width:5%"> Action </th>
            </tr>
        </thead>
        <tbody>
            @{
                int index = 0;
                foreach (var trainning in Model)
                {
                    string[] subs = @trainning.EXPECTED_DATE.ToString().Split(' ');
                    
                    <tr id="row_@trainning.TRAINNING_ID">
                        <td>@(++index)</td>
                        @*<td>@trainning.CMP_NAME</td>*@
                        @*<td>@trainning.DEPT_NAME</td>
                        <td>@trainning.SUB_NAME</td>*@
                        <td>@trainning.TRAINNING_NAME</td>
                        <td>@subs[0]</td>
                        <td>@trainning.STATUS</td>
                        <td>
                            <a href="/WorkforceTrainning/EditTrainning/@trainning.TRAINNING_ID" class="btn btn-tbl-edit">
                                <i class="material-icons">create</i>
                            </a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
<script>
    $("document").ready(function () {
        $('#tableExport').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy',
                'csv',
                'excel',
                'pdf',
                'print'
            ]
        });
    });
</script>