CodeBase/WfmWebPortal/Lms.Web.Portal/Controllers/ApprovalsController.cs
using Lms.Web.Portal.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Wfm.App.BL;
using Wfm.App.Common;
using Wfm.App.Core;
using Wfm.App.Core.Model;

namespace Lms.Web.Portal.Controllers
{
    [SessionExpire]
    [WfmAuthorize]
    public class ApprovalsController : Controller
    {
        // GET: Approvals
        private IBaseBL baseBL;
        public ApprovalsController(IBaseBL baseBL)
        {
            this.baseBL = baseBL;
        }

        #region workforcetrainning


        public ActionResult workforcetrainning()
        {
            WorkforceApprovalMetaData metaData = new WorkforceApprovalMetaData();

            AccountValidateUser_Result loggedin_user = Session["USER"] as AccountValidateUser_Result;
            var deptList = this.baseBL.DepartmentBL.GetDepartmentsByUserId(loggedin_user.COMPANY_ID, loggedin_user.USER_ID);
            var onRollOrContracts = this.baseBL.IDCardGenerationBL.GetOnRollOrContracts(loggedin_user.COMPANY_ID);
            var defaultBind = deptList.Select(x => x.DEPT_ID).FirstOrDefault();
            metaData.DEPARTMENT_ID = defaultBind;
            metaData.Departments = new SelectList(deptList, "DEPT_ID", "DEPT_NAME");
            metaData.OnRollOrContracts = new SelectList(onRollOrContracts, "WF_EMP_TYPE", "EMP_TYPE");
            metaData.Status = "N";
            ViewBag.Buildings = new SelectList(baseBL.ManPowerRequestBL.GetBuildings(), "BUILDING_ID", "BUILDING_NAME");
            return View(metaData);

        }



        public ActionResult ParticalWorkforceTrainning(Guid deptId, Guid? sub_dept_id, int? emptype_id, string status, Guid BUILDING_ID)
        {
            List<TRAINNING_WORKFORCE_MAPPING> list = new List<TRAINNING_WORKFORCE_MAPPING>();
            list = baseBL.WorkforceTrainningBL.GetWorkForceTrainningForApprovalByDepartmentId(deptId, sub_dept_id, emptype_id, status, BUILDING_ID);
            return View("_WorkforceTrainning", list);
        }
        [HttpPost]
        public ActionResult WorkForceTrainningApprovals(IEnumerable<Guid> twfmIds, FormCollection fm)
        {
            string remark = fm["Remark"];
            if (fm["Approve"] == "Approve")
            {
                baseBL.WorkforceTrainningBL.UpdateWorkForceTrainningByMappingId(twfmIds, "Y", remark);
            }
            else if (fm["Reject"] == "Reject")
            {
                baseBL.WorkforceTrainningBL.UpdateWorkForceTrainningByMappingId(twfmIds, "N", remark);
            }
            return RedirectToAction("workforcetrainning");
        }

        #endregion

        #region MRF
        public ActionResult mrfapprovals()
        {
            WorkforceApprovalMetaData metaData = new WorkforceApprovalMetaData();

            AccountValidateUser_Result loggedin_user = Session["USER"] as AccountValidateUser_Result;
            var deptList = this.baseBL.DepartmentBL.GetDepartmentsByUserId(loggedin_user.COMPANY_ID, loggedin_user.USER_ID);
            metaData.Departments = new SelectList(deptList, "DEPT_ID", "DEPT_NAME");
            ViewBag.Buildings = new SelectList(baseBL.ManPowerRequestBL.GetBuildings(), "BUILDING_ID", "BUILDING_NAME");
            return View(metaData);

        }
        public ActionResult ParticalMRFApprovals(string deptId, Guid? sub_dept_id, string status, Guid BUILDING_ID)
        {
            Guid deptid = new Guid();
            if (!string.IsNullOrEmpty(deptId))
            {
                deptid = new Guid(deptId);
            }
            AccountValidateUser_Result loggedin_user = Session["USER"] as AccountValidateUser_Result;
            List<MRFApprovalMetadata> datas = baseBL.ManPowerRequestBL.GetMRFApprovalByDepartmentId(deptid, sub_dept_id, status, BUILDING_ID);
            ViewBag.LoginUerrId = loggedin_user.USER_ID;
            return View("_MRFApprovals", datas);
        }
        [HttpPost]
        public ActionResult MRFApprovals(IEnumerable<Guid> twfmIds, FormCollection fm)
        {
            var mrfSearchULR = string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~")) + "/ManPowerRequest/Edit?mrf_INETRNAL_ID=";
            string remark = fm["Remark"];
            if (fm["Approve"] == "Approve")
            {
                baseBL.ManPowerRequestBL.UpdatMRFApprovalsByMappingId(twfmIds, "Y", remark, mrfSearchULR);
            }
            else if (fm["Reject"] == "Reject")
            {
                baseBL.ManPowerRequestBL.UpdatMRFApprovalsByMappingId(twfmIds, "N", remark, mrfSearchULR);
            }
            return RedirectToAction("mrfapprovals");
        }
        #endregion

        #region Exit Approval
        public ActionResult exitapprovals()
        {

            WorkforceApprovalMetaData metaData = new WorkforceApprovalMetaData();

            AccountValidateUser_Result loggedin_user = Session["USER"] as AccountValidateUser_Result;
            var deptList = this.baseBL.DepartmentBL.GetDepartmentsByUserId(loggedin_user.COMPANY_ID, loggedin_user.USER_ID);
            metaData.Departments = new SelectList(deptList, "DEPT_ID", "DEPT_NAME");
            metaData.Status = "Open";
            ViewBag.Buildings = new SelectList(baseBL.ManPowerRequestBL.GetBuildings(), "BUILDING_ID", "BUILDING_NAME");
            return View(metaData);

        }
        public ActionResult ParticalExitApprovals(string deptId, Guid? sub_dept_id, string status, Guid BUILDING_ID)
        {
            Guid deptid = new Guid();
            if (!string.IsNullOrEmpty(deptId))
            {
                deptid = new Guid(deptId);
            }
            AccountValidateUser_Result loggedin_user = Session["USER"] as AccountValidateUser_Result;
            List<ExitApprovalMetaData> datas = baseBL.AssetBL.GetExitApprovals(deptid, sub_dept_id, status, BUILDING_ID);
            ViewBag.LoginUerrId = loggedin_user.USER_ID;
            return View("_ExitApprovals", datas);
        }
        [HttpPost]
        public ActionResult ExitApprovals(IEnumerable<Guid> twfmIds, FormCollection fm)
        {
            var exitSearchULR = string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~")) + "/ExitManagement/EmployeeDetail";
            string remark = fm["Remark"];
            if (fm["Approve"] == "Approve")
            {
                baseBL.AssetBL.UpdatExitApprovalsByMappingId(twfmIds, "Y", remark, exitSearchULR);
            }
            else if (fm["Reject"] == "Reject")
            {
                baseBL.AssetBL.UpdatExitApprovalsByMappingId(twfmIds, "N", remark, exitSearchULR);
            }
            return RedirectToAction("exitapprovals");
        }
        #endregion

        #region Transfer Approval  
        public ActionResult TransferApprovals()
        {
            WorkforceApprovalMetaData metaData = new WorkforceApprovalMetaData();
            AccountValidateUser_Result loggedin_user = Session["USER"] as AccountValidateUser_Result;
            var deptList = this.baseBL.DepartmentBL.GetDepartmentsByUserId(loggedin_user.COMPANY_ID, loggedin_user.USER_ID);
            metaData.Departments = new SelectList(deptList, "DEPT_ID", "DEPT_NAME");
            metaData.Status = "Open";
            ViewBag.Buildings = new SelectList(baseBL.ManPowerRequestBL.GetBuildings(), "BUILDING_ID", "BUILDING_NAME");
            return View(metaData);

        }

        public string TransferApprovalList(string deptId, string sub_dept_id, string status, string BUILDING_ID)
        {
            AccountValidateUser_Result loggedin_user = Session["USER"] as AccountValidateUser_Result;
            string datas = baseBL.AssetBL.TransferApprovalList(deptId, sub_dept_id, status, BUILDING_ID,"","");
            return datas;
        }
        public string TransferRequestList(string deptId, string sub_dept_id, string status, string BUILDING_ID)
        {
            AccountValidateUser_Result loggedin_user = Session["USER"] as AccountValidateUser_Result;
            string datas = baseBL.AssetBL.TransferApprovalList(deptId, sub_dept_id, status, BUILDING_ID, SessionHelper.Get<String>("Username"), SessionHelper.Get<String>("LoginType"));
            ViewBag.LoginUerrId = loggedin_user.USER_ID;
            return datas;
        }

        [HttpGet]
        public string ApprovedTransfer(string TransferID, string Remark)
        {
            AccountValidateUser_Result loggedin_user = Session["USER"] as AccountValidateUser_Result;
            string ApprovedBy = loggedin_user.USER_NAME;
            return baseBL.AssetBL.ApprovedTransfer(TransferID, ApprovedBy, Remark);
        }

        #endregion
    }

}

CodeBase/WfmWebPortal/Lms.Web.Portal/Views/Approvals/_ExitApprovals.cshtml
@model IList<Wfm.App.Core.Model.ExitApprovalMetaData>
@{
    Layout = null;
}
<div class="table-responsive">
    @using (Html.BeginForm("ExitApprovals", "Approvals", FormMethod.Post))
    {
        <div class="row">
            <div class="col-9">
                <label class="col-12">Remark</label>
                @Html.TextArea("Remark")
            </div>
            <div class="col-sm-3" style="margin-top:20px">
                <div class="form-group">
                    <input type="submit" id="btnApprove" name="Approve" class="btn btn-primary waves-effect m-r-15" value="Approve" />
                    <input type="submit" id="btnSubmit" name="Reject" class="btn btn-primary waves-effect m-r-15" value="Reject" />
                </div>
            </div>

        </div>
        <div class="row">

        </div>
        <table id="tableExport"
               class="display table table-hover table-checkable order-column m-t-20 width-per-100">
            <thead>
                <tr>
                    <th>
                        <label>
                            <input type="checkbox" class="filled-in" id="checkAll" />
                            <span></span>
                        </label>
                    </th>
                    <th>Approver</th>
                    <th>Is Approved</th>
                    <th>Workforce/Code</th>
                    <th>Serveing Notice/Day</th>
                    <th>Resignation/Exit Date</th>
                    <th>Reason Of Leaving</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @*@if (ViewBag.LoginUerrId == item.USER_ID && item.APPROVER_STATUS == "")*@
                            @if (item.APPROVER_STATUS == "No")
                            {
                                <label>
                                    <input type="checkbox" name="twfmIds" class="filled-in" value="@item.EXIT_APPROVER_ID" />
                                    <span></span>
                                </label>
                            }
                        </td>
                        <td>@item.APPROVER_NAME</td>
                        <td>@item.APPROVER_STATUS</td>
                        <td>@item.WORKFORCE_NAME/@item.EMP_ID</td>
                        <td>@item.IS_NOTICE_SERVE/@item.NOTICE_DAYS Days</td>
                        <td>@Convert.ToDateTime(item.RESIGNATION_DATE).ToString("dd/MM/yyyy")--@Convert.ToDateTime(item.EXIT_DATE.Value.AddDays(item.NOTICE_DAYS)).ToString("dd/MM/yyyy")</td>
                        <td>@item.REASON_OF_LEAVING</td>
                    </tr>
                }

            </tbody>
        </table>
    }
</div>

CodeBase/WfmWebPortal/Lms.Web.Portal/Views/Approvals/_MRFApprovals.cshtml
@model IList<Wfm.App.Core.Model.MRFApprovalMetadata>
@{
    Layout = null;
}
<div class="table-responsive">
    @using (Html.BeginForm("MRFApprovals", "Approvals", FormMethod.Post))
    {
    <div class="row">
        <div class="col-8">
            <label class="col-12">Remark</label>
            @Html.TextArea("Remark")
        </div>
        <div class="col-sm-4" style="margin-top:25px">
            <div class="form-group">
                <input type="submit" id="btnSubmit" name="Reject" class="btn btn-primary  pull-right waves-effect m-r-15" value="Reject" />
                <input type="submit" id="btnApprove" name="Approve" class="btn btn-primary  pull-right waves-effect m-r-15" value="Approve" />

            </div>
        </div>
    </div>
       <br />
        <table id="tableExport"
               class="display table table-hover table-checkable order-column m-t-20 width-per-100">
            <thead>
                <tr>
                    <th>
                        <label>
                            <input type="checkbox" class="filled-in" id="checkAll" />
                            <span></span>
                        </label>
                    </th>
                    <th>Approver</th>
                    <th>Is Approved</th>
                    <th>S.No</th>
                    <th>MRF</th>
                    <th>Building/Floor</th>
                    <th>Skill/Designation</th>
                    <th>Quantity</th>
                    <th>Type</th>
                    <th>Status</th>
                    <th>Date of MRF</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @if (ViewBag.LoginUerrId == item.USER_ID && item.APPROVER_STATUS == "")
                            {
                                <label>
                                    <input type="checkbox" name="twfmIds" class="filled-in" value="@item.MRF_APPROVER_ID" />
                                    <span></span>
                                </label>
                            }
                        </td>
                        <td>@item.USER_NAME</td>
                        <td>@item.APPROVER_STATUS</td>
                        <td>@item.MRF_CODE.ToString("00000")</td>
                        <td>@item.REC_NAME</td>
                        <td>@item.BUILDING_NAME/@item.FLOOR_NAME</td>
                        <td>@item.SKILL_NAME/@item.WF_DESIGNATION_NAME</td>
                        <td>@item.QUANTITY</td>
                        <td>@item.EMP_TYPE</td>
                        <td>@item.MRF_STATUS</td>
                        <td>@item.MRF_Date</td>
                    </tr>
                }

            </tbody>
        </table>
    }
</div>

<script>
    $("document").ready(function () {
        $('#tableExport').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy',
                'csv',
                'excel',
                'pdf',
                'print'
            ]
        });
    });
</script>

CodeBase/WfmWebPortal/Lms.Web.Portal/Views/Approvals/_WorkforceTrainning.cshtml
@model IEnumerable<Wfm.App.Core.Model.TRAINNING_WORKFORCE_MAPPING>
@{
    Layout = null;
}
<div class="table-responsive">
    @using (Html.BeginForm("WorkForceTrainningApprovals", "Approvals", FormMethod.Post))
    {
    <div class="row">
        <div class="col-9">
            <label class="col-12">Remark</label>
            @Html.TextArea("Remark")
        </div>
        <div class="col-sm-3" style="margin-top:20px">
            <div class="form-group">
                <input type="submit" id="btnSubmit" name="Approve" class="btn btn-primary waves-effect m-r-15" value="Approve" />
            </div>
        </div>
      
    </div>
      
        <table class="table table-bordered table-striped table-hover js-basic-example dataTable" width="100%">
            <thead>
                <tr>
                    <th>
                        <label>
                            <input type="checkbox" class="filled-in" id="checkAll" />
                            <span></span>
                        </label>
                    </th>
                    <th>Name</th>
                    <th>Code</th>
                    <th>Trainning Name</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Is Completed </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <label>
                                <input type="checkbox" name="twfmIds" class="filled-in" value="@item.TRAINNING_MAPPING_ID" />
                                <span></span>
                            </label>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.WORKFORCE_NAME)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.WORKFORCE_CODE)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TRAINNING_NAME)
                        </td>

                        <td>
                            @Convert.ToDateTime(item.TRAINNING_START_DATE).ToString("dd/MM/yyyy")

                        </td>
                        <td>
                            @Convert.ToDateTime(item.TRAINNING_END_DATE).ToString("dd/MM/yyyy")
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ISTRAINNINGCOMPLETED)
                        </td>

                    </tr>
                }
            </tbody>
        </table>
    }
</div>

CodeBase/WfmWebPortal/Lms.Web.Portal/Views/Approvals/exitapprovals.cshtml
@model Wfm.App.Core.Model.WorkforceApprovalMetaData
@{

}
<section class="content">
    <div class="container-fluid">

        <div class="block-header">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="breadcrumb breadcrumb-style ">
                        <li class="breadcrumb-item">
                            <h4 class="page-title">Exit Approval</h4>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="/Approvals/mrfapprovals">
                                <i class="fas fa-layer-group"></i>Exit Request
                            </a>
                        </li>
                        <li class="breadcrumb-item active">List</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            <strong>Exit</strong>  Request List
                        </h2>
                    </div>
                    <div class="row col-12">
                        <div class="col-sm-3">
                            <div class="form-group">
                                <div class="form-line">
                                    @Html.LabelFor(x => x.BUILDING_ID, "Unit", new { @class = "required" })
                                    @Html.DropDownListFor(x => x.BUILDING_ID, ViewBag.Buildings as SelectList, "-- Select--", new { id = "BUILDING_ID", required = "true", @onchange = "onBuildingChange()" })
                                    @Html.ValidationMessageFor(m => m.BUILDING_ID)
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group">
                                <div class="form-line">
                                    @Html.LabelFor(x => x.DEPARTMENT_ID, "Department")
                                    @Html.DropDownListFor(x => x.DEPARTMENT_ID, Model.Departments, "All", new { required = "true" })
                                    @Html.ValidationMessageFor(m => m.DEPARTMENT_ID)
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="form-group">
                                <div class="form-line">
                                    @Html.LabelFor(x => x.SUBDEPT_ID, "Sub Department")
                                    @Html.DropDownListFor(x => x.SUBDEPT_ID, Enumerable.Empty<SelectListItem>(), "All", new { required = "true" })
                                    @Html.ValidationMessageFor(m => m.SUBDEPT_ID)
                                    @*@Html.HiddenFor(x => x.Con_MSG, new { id = "Con_MSG" })*@
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-2">
                            <div class="form-group">
                                <div class="form-line">
                                    @Html.LabelFor(x => x.Status, "Approval Status")

                                    @Html.DropDownListFor(m => m.Status, new List<SelectListItem>
                                       {
                                           new SelectListItem{ Text="Yes", Value = "Y" },
                                           new SelectListItem{ Text="No", Value = "N" },
                                        }, "All", new { required = "true" })
                                    @Html.ValidationMessageFor(m => m.Status)
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-1" style="margin-top:20px">
                            <div class="form-group">
                                <div class="form-line">
                                    <button type="button" class="btn btn-primary" onclick="GetEmployeeData()">Search</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="body">
                        <div id="particalDiv">

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

<script>
    $(window).on('load', function () {
        $(".page-loader-wrapper,.page-loader-wrapper").remove();
        GetEmployeeData();
    })
    $(document).ready(function () {
        $('#DEPARTMENT_ID').find('option').not(':first').remove();
    });
   
    $("#DEPARTMENT_ID").change(function () {
        getSubDeptbyDeptId();
    });

    function getSubDeptbyDeptId() {
        var DEPARTMENT_ID = $("#DEPARTMENT_ID").val();
        if (DEPARTMENT_ID != null) {
            $.get('/Dashboard/GetSubDepartmentByDepartmentId?departmentId=' + DEPARTMENT_ID, function (data) {
                $('#SUBDEPT_ID').find('option').not(':first').remove();
                $.each(data, function (i, item) {
                    $('#SUBDEPT_ID').append($('<option>', {
                        value: item.SUBDEPT_ID,
                        text: item.SUBDEPT_NAME
                    }));
                });
                $('#SUBDEPT_ID').formSelect();
                //GetEmployeeData();
            });
        } else {
            $('#SUBDEPT_ID').find('option').not(':first').remove();
            $('#SUBDEPT_ID').formSelect();
            //GetEmployeeData();
        }
    }
   
    function GetEmployeeData() {
        var DEPARTMENT_ID = $("#DEPARTMENT_ID").val();
        var SUBDEPT_ID = $("#SUBDEPT_ID").val();
        var status = $("#Status").val();
        var BUILDING_ID = $("#BUILDING_ID").val() ||'00000000-0000-0000-0000-000000000000';
        $("#particalDiv").empty();
    
            $.ajax(
                {
                    type: 'Get',
                    url: '/Approvals/ParticalExitApprovals?deptId=' + DEPARTMENT_ID + '&sub_dept_id=' + SUBDEPT_ID + "&status=" + status + '&BUILDING_ID=' + BUILDING_ID,
                    beforeSend: function () {
                        $('.page-loader-wrapper').show();
                    },
                    complete: function () {
                        $('.page-loader-wrapper').hide();
                    },

                    success:
                        function (response) {
                            $("#particalDiv").append(response);
                        },
                    error:
                        function (response) {
                            alert("Error: " + response);
                        }
                });
    }

    $(document).on('click', "#checkAll", function () {
        $("input[name='twfmIds']").attr("checked", this.checked);

        $("input[name='twfmIds']").click(function () {
            if ($("input[name='twfmIds']").length == $("input[name='twfmIds']:checked").length) {
                $("#checkAll").attr("checked", "checked");
            }
            else {
                $("#checkAll").removeAttr("checked");
            }
        });
    });

    function onBuildingChange() {
        var buildingId = $("#BUILDING_ID option:selected").val();
        $.get('/ManPowerRequest/GetFloorByBuildingId?buildingId=' + buildingId, function (data) {
            $('#DEPARTMENT_ID').find('option').not(':first').remove();
            $.each(data, function (i, item) {
                $('#DEPARTMENT_ID').append($('<option>', {
                    value: item.DEPT_ID,
                    text: item.DEPT_NAME
                }));
            });
            $('#DEPARTMENT_ID').formSelect();
        });
    }
   

    $(document).on('click', "#btnApprove", function () {
        var count = $("input[name='twfmIds']:checked").length;
        if (count == 0) {
            alert("No rows selected");
            return false;
        }
        else if (confirm('Are You sure ? You want to Approve.')) {

        } else {
            return false;
        }
    });
    $(document).on('click', "#btnSubmit", function () {
        var count = $("input[name='twfmIds']:checked").length;
        if (count == 0) {
            alert("No rows selected");
            return false;
        } else if ($("#Remark").val() == '') {
            alert("Remark is mendatory.");
            return false;
        } else if (confirm('Are You sure ? You want to Reject.')) {

        }
        else {
            return false;
        }
    });
</script>