CodeBase/WfmWebPortal/Lms.Web.Portal/Controllers/SalaryRevisionController.cs
using Lms.Web.Portal.Authorization;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using Wfm.App.BL;
using Wfm.App.Core;
using Wfm.App.Core.Model;
using Lms.Web.Portal.DataAccess;
using System.Data;

namespace Lms.Web.Portal.Controllers
{
    public class SalaryRevisionController : Controller
    {
        private IBaseBL baseBl;


        public SalaryRevisionController(IBaseBL baseBl)
        {
            this.baseBl = baseBl;
        }
        [HttpGet]
        public string GetBasicSalary(string SKILL_ID)
        {
            DLLReports objDB = new DLLReports();
            DataSet ds = new DataSet();
             ds = objDB.GetBasicSalary("Proc_SalaryRevision","",SKILL_ID, "", "", "","1");

            return ds.GetXml();
        }
        public string SubmitSalaryRevision(string WF_EMP_TYPE, string SKILL_ID, string BASIC_SALARY, string PERCENTAGE, string WEF)
        {
            DLLReports objDB = new DLLReports();
            DataSet ds = new DataSet();
            ds = objDB.GetBasicSalary("Proc_SalaryRevision", WF_EMP_TYPE, SKILL_ID, BASIC_SALARY, PERCENTAGE, WEF,"2");

            return ds.GetXml();
        }
    }

}

CodeBase/WfmWebPortal/Lms.Web.Portal/Controllers/WorkforceController.cs
using Lms.Web.Portal.Authorization;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Wfm.App.BL;
using Wfm.App.Common;
using Wfm.App.Core;
using Wfm.App.Core.Model;

namespace Lms.Web.Portal.Controllers
{
    [SessionExpire]
    [WfmAuthorize]
    public class WorkforceController : Controller
    {
        private IBaseBL baseBl;


        public WorkforceController(IBaseBL baseBl)
        {
            this.baseBl = baseBl;
        }


        [HttpPost]
        [Authorize]
        public JsonResult Search(WorkforceMetaData wfobj)
        {
            //WorkforceBL objwf = new WorkforceBL();
            //MasterDataBL mBL = new MasterDataBL();
            List<ManPowerRequestFormMetaDataList> mrfList = new List<ManPowerRequestFormMetaDataList>();
            ManPowerRequestFormMetaDataList objmrf = new ManPowerRequestFormMetaDataList();
            List<SelectListItem> empTypeList = new List<SelectListItem>();
            List<SelectListItem> designationList = new List<SelectListItem>();
            List<SelectListItem> skillList = new List<SelectListItem>();
            List<SelectListItem> WF_EMP_TYPELst = new List<SelectListItem>();

            mrfList = baseBl.WorkforceBL.GetActiveMRFList().Where(x => x.MRF_ID == wfobj.MRF_ID).ToList();

            if (mrfList != null)
            {
                objmrf = mrfList.FirstOrDefault();

                empTypeList = baseBl.MasterDataBL.GetEmpTypeList().Select(x =>
                                      new SelectListItem()
                                      {
                                          Text = x.EMP_TYPE.ToString(),
                                          Value = x.EMP_TYPE_ID.ToString()
                                      }).Where(f => f.Value == objmrf.WF_EMP_TYPE.ToString()).ToList();

                designationList = baseBl.MasterDataBL.GetDesignationList().Select(x =>
                          new SelectListItem()
                          {
                              Text = x.WF_DESIGNATION_NAME.ToString(),
                              Value = x.WF_DESIGNATION_ID.ToString()
                          }).Where(f => f.Value == objmrf.WF_DESIGNATION_ID.ToString()).ToList();

                skillList = baseBl.MasterDataBL.GetSkillList().Select(x =>
                          new SelectListItem()
                          {
                              Text = x.SKILL_NAME.ToString(),
                              Value = x.SKILL_ID.ToString()
                          }).Where(f => f.Value == objmrf.SKILL_ID.ToString()).ToList();

                WF_EMP_TYPELst = baseBl.MasterDataBL.GetWF_EMP_TYPE().Select(x =>
                          new SelectListItem()
                          {
                              Text = x.EMP_TYPE.ToString(),
                              Value = x.WF_EMP_TYPE.ToString()
                          }).Where(f => f.Value == objmrf.WF_EMP_TYPE.ToString()).ToList();
            }
            WorkforceMetaData wfMetaData = new WorkforceMetaData { EmpTypeList = empTypeList, SkillList = skillList, DesignationList = designationList, WF_EMP_TYPEList = WF_EMP_TYPELst };
            wfMetaData.MRF_INTERNAL_ID = objmrf.MRP_INETRNAL_ID;
            wfMetaData.WF_EMP_TYPE = objmrf.WF_EMP_TYPE;

            return Json(wfMetaData, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Authorize]
        public JsonResult EmpSalaryDetailSearch(WorkforceSalaryMetaData wfobj)
        {
            //WorkforceBL objwf = new WorkforceBL();

            WorkforceSalaryMetaData empsal = baseBl.WorkforceBL.Find(wfobj.EMP_ID);

            return Json(empsal, JsonRequestBehavior.AllowGet);
        }
        #region Special Allowance
        [HttpGet]
        public ActionResult SpecialAllowance()
        {
            SpecialAllowanceMetaData metaData = new SpecialAllowanceMetaData();
            AccountValidateUser_Result loggedin_user = Session["USER"] as AccountValidateUser_Result;
            var deptList = this.baseBl.DepartmentBL.GetDepartmentsByUserId(loggedin_user.COMPANY_ID, loggedin_user.USER_ID);
            var onRollOrContracts = this.baseBl.IDCardGenerationBL.GetOnRollOrContracts(loggedin_user.COMPANY_ID);
            metaData.Departments = new SelectList(deptList, "DEPT_ID", "DEPT_NAME");
            metaData.OnRollOrContracts = new SelectList(onRollOrContracts, "WF_EMP_TYPE", "EMP_TYPE");
            ViewBag.Months = DateTimeFormatInfo.InvariantInfo.MonthNames
            .Select((monthName, index) => new SelectListItem
            {
                Value = (index + 1).ToString(),
                Text = monthName
            }).Where(x => x.Text != "");

            ViewBag.Buildings = new SelectList(baseBl.ManPowerRequestBL.GetBuildings(), "BUILDING_ID", "BUILDING_NAME");
            ViewBag.Years = new SelectList(Enumerable.Range(DateTime.Today.Year - 1, 2).Select(x =>
                           new SelectListItem()
                           {
                               Text = x.ToString(),
                               Value = x.ToString()
                           }), "Value", "Text");

            return View(metaData);
        }

        [HttpPost]
        public ActionResult AddSpecialAllowance(SpecialAllowanceMetaData specialAllowance)
        {
            if (this.baseBl.WorkforceBL.AddSpecialAllowance(specialAllowance))
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
                return Json(false, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetSpecialAllowanceByDept(Guid? deptId, Guid? sub_dept_id, int? emptype_id, int? year_id, Guid? BUILDING_ID2)
        {
            List<SpecialAllowanceMetaData> specialAllowances = new List<SpecialAllowanceMetaData>();
            specialAllowances = this.baseBl.WorkforceBL.GetSpecialAllowanceByDept(deptId, sub_dept_id, emptype_id, year_id, BUILDING_ID2);
            return PartialView("_SpecialAllowance", specialAllowances);
        }

        public ActionResult GetSpecialAllowanceById(Guid id)
        {
            SpecialAllowanceMetaData specialAllowances = new SpecialAllowanceMetaData();
            specialAllowances = this.baseBl.WorkforceBL.GetSpecialAllowanceById(id);
            return Json(specialAllowances, JsonRequestBehavior.AllowGet);

        }
        public JsonResult LoadWorkforceByWFType(Guid deptId, Guid? sub_dept_id, string query, int? emp_type_id)
        {
            List<WorkforceMetaDataList> result = new List<WorkforceMetaDataList>();
            query = query.ToUpper();
            try
            {
                result = baseBl.WorkforceBL.GetEmpAllItems(deptId, sub_dept_id, emp_type_id, null).Where(x => x.EMP_NAME.ToUpper().Contains(query) || x.EMP_ID.ToUpper().Contains(query)).ToList();
                var list = (from q in result
                            select new { Name = string.Concat(q.EMP_NAME, " - ", q.EMP_ID), ID = q.WF_ID }).ToList();

                return Json(list, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(result, JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult LoadWorkforceByPIB(Guid deptId, Guid? sub_dept_id, string query, int? emp_type_id)
        {
            List<WorkforceMetaDataList> result = new List<WorkforceMetaDataList>();
            query = query.ToUpper();
            try
            {
                result = baseBl.WorkforceBL.GetEmpAllItems_PIB(deptId, sub_dept_id, emp_type_id, null).Where(x => x.EMP_NAME.ToUpper().Contains(query) || x.EMP_ID.ToUpper().Contains(query)).ToList();
                var list = (from q in result
                            select new { Name = string.Concat(q.EMP_NAME, " - ", q.EMP_ID), ID = q.WF_ID }).ToList();

                return Json(list, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(result, JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult LoadWorkforceByWFType_N(Guid BUILDING_ID, string query, Guid deptId, Guid? sub_dept_id, int? emp_type_id, int? EMPLOYMENT_TYPE)
        {
            List<WorkforceMetaDataList> result = new List<WorkforceMetaDataList>();
            query = query.ToUpper();
            try
            {
                result = baseBl.WorkforceBL.BindWorkforceByWFType_New(BUILDING_ID, deptId, sub_dept_id, emp_type_id, EMPLOYMENT_TYPE).Where(x => x.EMP_NAME.ToUpper().Contains(query) || x.EMP_ID.ToUpper().Contains(query)).ToList();
                var list = (from q in result
                            select new { Name = string.Concat(q.EMP_NAME, " - ", q.EMP_ID), ID = q.WF_ID }).ToList();

                return Json(list, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(result, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult BindWorkforceByWFType(Guid BUILDING_ID, Guid deptId, int? emp_type_id, Guid? sub_dept_id)
        {
            List<WorkforceMetaDataList> result = new List<WorkforceMetaDataList>();
            try
            {
                result = baseBl.WorkforceBL.BindWorkforceByWFType(deptId, sub_dept_id, emp_type_id, BUILDING_ID).ToList();
                ViewBag.Employeess = new SelectList(result);
                var list = (from q in result
                            select new { Name = q.EMP_NAME, ID = q.WF_ID }).ToList();
                return Json(list, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(result, JsonRequestBehavior.AllowGet);
            }
        }

        

CodeBase/WfmWebPortal/Lms.Web.Portal/Views/Workforce/DownloadSalarySlip - Copy.cshtml
@{
    Layout = null;
}

<table style="width: 100%; text-align: center; padding-left: 3%; padding-right:3%;">
    <tr>
        <td style="font-weight: bold;" colspan="15">[CMPNAME]</td>
    </tr>
    <tr>
        <td style="font-weight: bold;" colspan="15">[CMPNAME_ADDRESS]</td>
    </tr>
    <tr>
        <td style="font-weight: bold; outline: thin solid; height: 40px">EMP_CODE</td>
        <td style="font-weight: bold; outline: thin solid">[EMP_CODE]</td>
        <td colspan="13" style="text-align:right">Salary Slip for the Month of [MONTH_YY]</td>
    </tr>
    <tr><td colspan="15"></td></tr>
    <tr style="outline: thin solid">
        <td style="width: 50px; border-right: thin solid; width: 12%">Name</td>
        <td style="border-right: thin solid;width:12%">Department</td>
        <td style="border-right: thin solid; width: 12%">UAN</td>
        <td style="border-right: thin solid;">ESIC</td>
        <td style="width: 60px; border-right: thin solid;">Wages Rate</td>
        <td style="width: 40px; border-right: thin solid;">Actual Paid Days</td>
        <td style="width: 14%; border-right: thin solid;text-align:center" colspan="3">
            <table width="100%" style="text-align: center; border-collapse: collapse; border-style: hidden;">
                <tr >
                    <td style="border: 1px solid black;" colspan="3">Earned Wages</td>
                </tr>
                <tr>
                    <td style="width:50px;border: 1px solid black;">Basic + DA</td>
                    <td style="width:50px;border: 1px solid black;">HR Allowances</td>
                    <td style="width:50px;border: 1px solid black;">Total</td>
                </tr>
            </table>
        </td>
        <td style="width: 10%; border-right: thin solid;" colspan="3">
            <table width="100%" style="text-align: center; border-collapse: collapse; border-style: hidden;">
                <tr >
                    <td style="border: 1px solid black;" colspan="3">Deduction</td>
                </tr>
                <tr>
                    <td style="width:40px;border: 1px solid black;">P.F.</td>
                    <td style="width:40px;border: 1px solid black;">ESI</td>
                    <td style="width:40px;border: 1px solid black;">Fine / Advance</td>
                </tr>
            </table>
        </td>
        <td style="border-right: thin solid;width:55px;">Actual Wages Paid</td>
        <td style="width:10%;" colspan="2">
            <table width="100%" style="text-align: center; border-collapse: collapse; border-style: hidden;">
                <tr>
                    <td style="border: 1px solid black;" colspan="2">Employer's Contribution</td>
                </tr>
                <tr>
                    <td style="border: 1px solid black;">EPF</td>
                    <td style="border: 1px solid black;">ESI</td>
                </tr>
            </table>
        </td>
    </tr>
    <tr style="outline: thin solid">
        <td style="border-right: thin solid;">[EMP_NAME]</td>
        <td style="border-right: thin solid;">[DEPARTMENT]</td>
        <td style="border-right: thin solid;">[UAN]</td>
        <td style="border-right: thin solid;">[ESIC]</td>
        <td style="border-right: thin solid;">[WAGES_RATE]</td>
        <td style="border-right: thin solid;">[ACTUAL_PAID_DAY]</td>
        <td style="border-right: thin solid;">[BASIC_DA]</td>
        <td style="border-right: thin solid;">[HR_ALL]</td>
        <td style="border-right: thin solid;">[TOTAL]</td>
        <td style="border-right: thin solid;">[WF_EPF]</td>
        <td style="border-right: thin solid;">[WF_ESI]</td>
        <td style="border-right: thin solid;">[FINE_OR_ADVANCE]</td>
        <td style="border-right: thin solid;">[ACTUAL_WAGES_PAID]</td>
        <td style="border-right: thin solid;">[CONTRI_EPF]</td>
        <td>[CONTRI_ESI]</td>
    </tr>
    <tr>
        <td style="text-align: right; padding-right: 50px;font-weight:bold;height:80px;" colspan="15">(Signature of Employee)</td>
    </tr>
</table>

CodeBase/WfmWebPortal/Lms.Web.Portal/Views/Workforce/SearchDailyWork.cshtml
@model Wfm.App.Core.Model.FilterDailyWork

@{
    ViewBag.Title = "Workforce - Employees Salary";
    //@model IList<Wfm.App.Core.Model.WorkforceMetaDataList>

}

<section class="content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <ul class="breadcrumb breadcrumb-style ">
                        <li class="breadcrumb-item">
                            <h4 class="page-title">Workforce</h4>
                        </li>
                        <li class="breadcrumb-item bcrumb-1">
                            <a href="/Workforce/DailyWork">
                                <i class="fas fa-layer-group"></i> Workforce
                            </a>
                        </li>
                        <li class="breadcrumb-item active">View Daily Works</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            <strong>View </strong> Daily Work
                        </h2>
                    </div>


                    @using (Html.BeginForm(null, null, FormMethod.Post, new { @id = "filterDailyWork", @class = "login100-form validate-form" }))
                    {
                <div class="row col-12">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="form-line">
                                @Html.LabelFor(x => x.BUILDING_ID, "Unit", new { @class = "required" })
                                @Html.DropDownListFor(x => x.BUILDING_ID, ViewBag.Buildings as SelectList, "-- Select--", new { id = "BUILDING_ID", required = "true", @onchange = "onBuildingChange()" })
                                @Html.ValidationMessageFor(m => m.BUILDING_ID)
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="form-line">
                                @Html.LabelFor(x => x.DEPARTMENT_ID, "Department", new { @class = "required" })
                                @Html.DropDownListFor(x => x.DEPARTMENT_ID, Model.Departments, "-- Select --", new { required = "true" })
                                @Html.ValidationMessageFor(m => m.DEPARTMENT_ID)
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="form-line">
                                @Html.LabelFor(x => x.SUBDEPT_ID, "Sub Department", new { @class = "required" })
                                @Html.DropDownListFor(x => x.SUBDEPT_ID, Enumerable.Empty<SelectListItem>(), "--Select--", new { required = "true" })
                                @Html.ValidationMessageFor(m => m.SUBDEPT_ID)
                            </div>
                        </div>
                    </div>
                    
                </div>
                <div class="row col-12">
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="form-line">
                                @Html.LabelFor(x => x.WF_EMP_TYPE, "Workforce type")
                                @Html.DropDownListFor(x => x.WF_EMP_TYPE, Model.OnRollOrContracts, "All")
                                @Html.ValidationMessageFor(m => m.WF_EMP_TYPE)
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="form-line">
                                @Html.LabelFor(x => x.EMP_NAME, "Workforce Name")
                                @Html.DropDownListFor(x => x.EMP_NAME, new SelectList(ViewBag.EmpName, "Value", "Text"), "--Select--")
                                @Html.ValidationMessageFor(m => m.EMP_NAME)
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <div class="form-line">
                                <div class="row">
                                    <div class="col-sm-6">
                                        @Html.LabelFor(x => x.StartDate, "Work start date", new { @class = "required" })
                                        @Html.TextBoxFor(m => m.StartDate, "{0:dd/mm/yyyy}", new { required = "true", @class = "datepicker form-control" })
                                        @Html.ValidationMessageFor(m => m.StartDate)
                                    </div>
                                    <div class="col-sm-6">
                                        @Html.LabelFor(x => x.EndDate, "Work end date", new { @class = "required" })
                                        @Html.TextBoxFor(m => m.EndDate, "{0:dd/mm/yyyy}", new { required = "true", @class = "datepicker form-control" })
                                        @Html.ValidationMessageFor(m => m.EndDate)
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

                        <div class="row col-12">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-line">
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <div class="form-line">
                                        <button type="button" id="btnFilter" onclick="getSearchData()">Search</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="body" id="particalDiv">

                        </div>

                    }

                </div>
            </div>
        </div>
    </div>
</section>
<style type="text/css">
    .Show {
        display: block;
    }

    .Hide {
        display: none;
    }

    .ui-autocomplete {
        background-color: #f5f5f5;
        max-width: 500px;
        max-height: 200px;
        overflow-y: scroll;
        overflow-x: hidden;
        z-index: 100;
        border: 0px 1px 1px 1px;
    }

    .ui-menu-item .ui-menu-item-wrapper.ui-state-active {
        background-color: #DCDCDC;
        color: #000000;
    }

    .modal {
        position: fixed;
        top: 0;
        left: 0;
        z-index: 1050;
        display: none;
        width: 100%;
        height: auto !important;
        overflow: hidden;
        outline: 0;
    }
</style>
<script>
    var addItems = [];
    let items = [];
    var operations = [];
    $(document).ready(function () {
        $("select[required]").css({ display: "block", height: 0, padding: 0, width: 0, position: 'absolute' });
        $('#StartDate','#EndDate').bootstrapMaterialDatePicker({
            format: 'DD/MM/YYYY',
            clearButton: true,
            weekStart: 1,
            time: false
        });
        $('#DEPARTMENT_ID').find('option').not(':first').remove();
        $('#DEPARTMENT_ID').formSelect();
    });

    function onBuildingChange() {
        var buildingId = $("#BUILDING_ID option:selected").val();
        $.get('/ManPowerRequest/GetFloorByBuildingId?buildingId=' + buildingId, function (data) {
            $('#DEPARTMENT_ID').find('option').not(':first').remove();
            $.each(data, function (i, item) {
                $('#DEPARTMENT_ID').append($('<option>', {
                    value: item.DEPT_ID,
                    text: item.DEPT_NAME
                }));
            });
            $('#DEPARTMENT_ID').formSelect();
        });
    }

    $("#DEPARTMENT_ID").change(function () {
        $('#WF_EMP_TYPE').val('');
        $('#WF_EMP_TYPE').formSelect();
        $('#EMP_NAME').find('option').not(':first').remove();
        $('#EMP_NAME').formSelect();
        getSubDeptbyDeptId();
    });

    function getSubDeptbyDeptId() {
        var DEPARTMENT_ID = $("#DEPARTMENT_ID").val();
        if (DEPARTMENT_ID != null) {
            $.get('/Dashboard/GetSubDepartmentByDepartmentId?departmentId=' + DEPARTMENT_ID, function (data) {
                $('#SUBDEPT_ID').find('option').not(':first').remove();
                $.each(data, function (i, item) {
                    $('#SUBDEPT_ID').append($('<option>', {
                        value: item.SUBDEPT_ID,
                        text: item.SUBDEPT_NAME
                    }));
                });
                $('#SUBDEPT_ID').formSelect();
                getDepartmentItemsData();
            });
        } else {
            $('#SUBDEPT_ID').find('option').not(':first').remove();
            $('#SUBDEPT_ID').formSelect();
        }
    }

    $("#WF_EMP_TYPE").change(function () {
          $("#EMP_NAME").val("");
         $.ajax({
                url: '@Url.Action("PiecWagerWorkforceByWFType", "Workforce")',
                datatype: "json",
                data: {
                    deptId: $("#DEPARTMENT_ID").val(),
                    sub_dept_id:$("#SUBDEPT_ID").val(),
                    query: $('#EMP_NAME').val(),
                    emp_type_id: $('#WF_EMP_TYPE').val()
                },
             success: function (data) {
                 debugger;
                 $('#EMP_NAME').find('option').not(':first').remove();
                 $.each(data, function (i, item) {
                     $('#EMP_NAME').append($('<option>', {
                         value: item.ID,
                         text: item.Name
                     }));
                 });
                 $('#EMP_NAME').formSelect();
                  
                }
            })
    });

    function getSearchData() {
        var DEPARTMENT_ID = $("#DEPARTMENT_ID").val();
        var WF_EMP_TYPE = $("#WF_EMP_TYPE").val();
        var wf_id = $("#EMP_NAME").val();
        var startDate = $("#StartDate").val();
        var endDate = $("#EndDate").val();
        if ($("#filterDailyWork").valid()) {
            $("#particalDiv").empty();
            var filterDailyWork = { DEPARTMENT_ID: DEPARTMENT_ID, WF_ID: wf_id, WF_EMP_TYPE: WF_EMP_TYPE, StartDate: startDate, EndDate: endDate };
            $.ajax({
                type: "POST",
                url: '/Workforce/SearchDailyWork',     //your action
                data: filterDailyWork,   //your form name.it takes all the values of model
                beforeSend: function () {
                    $('.page-loader-wrapper').show();
                },
                complete: function () {
                    $('.page-loader-wrapper').hide();
                },

                success: function (result) {
                    $("#particalDiv").append(result);
                    return false;
                },
                error:
                    function (response) {
                        alert("Error: " + response);
                    }
            });
        } else {
            return false;
        }
    }
    $("#EMP_NAME").keyup(function () {
      var name=  $("#EMP_NAME").val();
        if (name.length === 0) {
            $("#WF_ID").val("");
        }
    });
     @*$("#EMP_NAME").autocomplete({
        max: 10,
        minLength: 1,
        source: function (request, response) {
            $.ajax({
                url: '@Url.Action("PiecWagerWorkforceByWFType", "Workforce")',
                datatype: "json",
                data: {
                    deptId: $("#DEPARTMENT_ID").val(),
                    query: $('#EMP_NAME').val(),
                    emp_type_id: $('#WF_EMP_TYPE').val()
                },
                success: function (data) {
                    response($.map(data, function (val, item) {
                        return {
                            label: val.Name,
                            value: val.Name,
                            empId: val.ID
                        }
                    }))
                }
            })
        },
        select: function (event, ui) {
            $("#WF_ID").val(ui.item.empId);
        },
         open: function (event, ui) {
             $(this).removeClass("ui-corner-all").addClass("ui-corner-top");
        },
         close: function (event, ui) {
            $(this).removeClass("ui-corner-top").addClass("ui-corner-all");
        }
    });*@

</script>

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

CodeBase/WfmWebPortal/Lms.Web.Portal/Views/Workforce/_EmployeesSalary.cshtml
@model IEnumerable<Wfm.App.Core.Model.WorkforceMetaDataList>
<div class="table-responsive">
    <table id="tableExport"
          class="table table-bordered table-striped table-hover js-basic-example dataTable" width="100%">
        <thead>
            <tr>
                <th>S.No</th>
                <th>Employee Id</th>
                <th>Name</th>
                <th>Contact No.</th>
                <th>Department</th>
                <th>Designation</th>
                <th>Date of Joining</th>
                <th>Aadhar No.</th>
                <th>Status</th>
                <th>Edit</th>
                @*<th></th>*@
            </tr>
        </thead>
        <tbody>
            @{int index = 1;}
            @foreach (var item in Model)
            {
                <tr>
                    <td>  @index</td>
                    <td>@item.EMP_ID</td>
                    <td>@item.EMP_NAME</td>
                    <td>@item.MOBILE_NO</td>
                    <td>@item.DEPT</td>
                    <td>@item.WF_DESIGNATION</td>
                    <td>@Wfm.App.Common.Utility.FormatDate(@item.DOJ)</td>
                    <td>@item.AADHAR_NO</td>
                    <td>@item.STATUS</td>
                    <td>
                        <a href="/Workforce/Salary?wfid=@item.EMP_ID">
                            <i class="fas fa-edit"></i>
                        </a>
                    </td>
                </tr>
                index++;
            }

        </tbody>
    </table>
</div>
<script>
    $("document").ready(function () {
        $('#tableExport').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy',
                'csv',
                'excel',
                'pdf',
                'print'
            ]
        });
    });
</script>